### ISSUE TITLE
Message could be changed for HTTP Normal channel after Send method called.

### ISSUE THREAD

**Issue by MichaelDysart** [TaylorAbraham/Covert-Channels#41]
In the Send method for an HTTP Normal channel in server mode, the input data field is sent along a go channel on lines 157 and 164. If the server has to wait for a GET request, then since the data field is a slice (i.e. pointer to an array) the data in the array on the channel could change if the user modifies the input array after calling the Send method.

The data in the data slice should be copied to a new buffer prior to sending along the go channel.

**Comment by JacksonSchoe** [comment]
so is all you want a new buffer holding the same information that is about to be returned on line 157? Ie uint64(len(buf.Bytes()))? Sorry I know that was probably a dumb question, I guess Im just not really sure what data slice you are referring to

**Comment by MichaelDysart** [comment]
@JacksonSchoe On line 157 there is the following code:
                   `c.serverSendBuf <- data:`

What that does is send the variable data along a channel. Think of it as a fifo queue that is synchronized, like the producer consumer problems we have discussed in previous classes.

Now c.serverSendBuf is a buffered channel. That means that while a read from the channel will block until data is present on the channel, a send on the channel will not block, but will instead put the variable onto the queue (so long as the queue is not full).

The key thing to keep in mind is that the type of data that is sent along a channel matters. In other words, the data could be a value or a pointer. Think of it as a function call. If you pass a variable by value, the changing the original value will not affect how the function behaves. If you pass a variable by reference (as a pointer), then changing the original value might alter how the function behaves.

This is a problem because of the datatype that is `data`. Notice the top of the function, the type is `[]byte`. That means that the datatype is a slice. Think of it as a pointer to an array that includes length information to prevent out of bounds accesses. But it also means that someone outside of the function could modify `data` and change the value inside of the function.

The combination of the above facts leads to a problem. Suppose I call `Send(myData)` with the slice `myData`. When `Send` occurs, `myData` is sent along the buffered channel. But, because the channel is buffered, the `Send` method returns immediately even though the data has not necessarily actually been sent in a GET response. That means, that if I update `myData` after calling `Send`, then the data actually sent across the covert channel may change.

The solution is to copy the message in `data` to a new slice so that even if the original slice is modified, the data sent on the channel will stay the same.

You could to this with the copy method:
```
var dataCopy []byte = make([]byte, len(data))
copy(dataCopy, data)
```

You could also append to an empty slice. I have heard that this is slightly faster.
```
data = append([]byte{}, data)
```
This would be done at the top of the `Send` method.

**Comment by JacksonSchoe** [comment]
resolved
