### ISSUE TITLE
Http Covert and Normal channel are not functioning properly when tested in the UI.

### ISSUE THREAD

**Issue by JacksonSchoe** [TaylorAbraham/Covert-Channels#44]
Here is the error from when I tried opening a server which threw an error, then tried opening the client which proceed to repeatedly through an error. I may be running an outdated version of the ui but Im not entirely sure its to blame. I have no idea where to start. Any help would be much appreciated. Here is the error log: 
Connection to server established.
[ERROR]: Unable to open channel: listen tcp4 :8124: socket: too many open files
Covert channel successfully opened.
[ERROR]: Read fail: Read 0 bytes out of 1024 available bytes: Get http://127.0.0.1:8123/: dial tcp 127.0.0.1:8123: connect: connection refused
[ERROR]: Read fail: Read 0 bytes out of 1024 available bytes: Get http://127.0.0.1:8123/: dial tcp 127.0.0.1:8123: connect: connection refused
[ERROR]: Read fail: Read 0 bytes out of 1024 available bytes: Get http://127.0.0.1:8123/: dial tcp 127.0.0.1:8123: connect: connection refused

**Comment by MichaelDysart** [comment]
I do not get an error when opening the server. Did you make sure to start up two servers and connect separately to them?
Did you set the port numbers as different? Did you set up separate servers with different port numbers, and swap http channel port values between them?

As for the client repeatedly returning nothing, that is expected from your code.
Remember, the client makes GET requests to the server. If there is no message ready to send, then the client just gets the response and returns with nothing. The way the Controller works is to repeatedly attempt to read from the covert channel. For the client, this means repeated GET requests, whether there is data waiting or not.

You have to decide how to handle that.
You could increase the timeout on the server to force the client to make fewer requests.
You could put a flag in the http response to indicate if there is data coming back. If data is received, the read returns. If there is no data, the client http channel could wait for a few seconds before making another request for data.
